### ISSUE TITLE
Lowercase hex color

### ISSUE THREAD

**Issue by miirinjej** [gu-fan/colorv.vim#30]
`"let g:colorv_uppercase = 0"` does not work for me.
I get this value `"#FF0000"` when edit/insert color, instead `"#ff0000"`.
Can you add `"g:colorv_lowercase = 1"` option? Or some like this `"let g:colorv_uppercase = 0"` or this `"let g:colorv_case = 'upper|lower'"`.
Thank you!

**Comment by aaron-goshine** [comment]
fix
https://github.com/gu-fan/colorv.vim/pull/31
